In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import sklearn.metrics

In [17]:
variables_entrada = ['age', 'gender', 'daily_gaming_hours', 'game_genre', 'sleep_hours', 'sleep_quality',
       'sleep_disruption_frequency', 'academic_work_performance', 'grades_gpa',
       'work_productivity_score', 'mood_state', 'mood_swing_frequency',
       'withdrawal_symptoms', 'loss_of_other_interests',
       'continued_despite_problems', 'eye_strain', 'back_neck_pain',
       'weight_change_kg', 'exercise_hours_weekly', 'social_isolation_score',
       'face_to_face_social_hours_weekly', 'monthly_game_spending_usd',
       'years_gaming']
variable_salida = 'gaming_addiction_risk_level'

datos = pd.read_csv('Gaming and Mental Health.csv', delimiter=',', header=0)

X = datos.loc[:, variables_entrada].copy()
y = datos.loc[:, variable_salida].copy()

In [35]:
X.columns

Index(['age', 'gender', 'daily_gaming_hours', 'game_genre', 'sleep_hours',
       'sleep_quality', 'sleep_disruption_frequency',
       'academic_work_performance', 'grades_gpa', 'work_productivity_score',
       'mood_state', 'mood_swing_frequency', 'withdrawal_symptoms',
       'loss_of_other_interests', 'continued_despite_problems', 'eye_strain',
       'back_neck_pain', 'weight_change_kg', 'exercise_hours_weekly',
       'social_isolation_score', 'face_to_face_social_hours_weekly',
       'monthly_game_spending_usd', 'years_gaming'],
      dtype='object')

#### Variables numéricas:

que mierda significa tener un work_productivity_score de 6 ???? es todo lo subjetivo

que mierda es el social_isolation_score y en que se basa

grades_gpa va de 1 a 4, puta mierda de americanadas

In [31]:
X.describe()

,age,daily_gaming_hours,sleep_hours,grades_gpa,work_productivity_score,weight_change_kg,exercise_hours_weekly,social_isolation_score,face_to_face_social_hours_weekly,monthly_game_spending_usd,years_gaming
count,1000.000000,1000.000000,1000.000000,754.000000,674.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,20.475000,6.151400,5.738100,2.518037,5.394659,1.513400,6.945900,3.872000,7.654500,105.219730,5.796000
std,4.116105,2.867194,1.441213,0.872312,2.898742,1.432212,1.805027,2.091409,3.751954,113.886768,3.775532
min,13.000000,0.500000,3.000000,1.010000,1.000000,0.000000,0.700000,1.000000,0.000000,0.100000,1.000000
25%,18.000000,4.100000,4.800000,1.760000,3.000000,0.400000,5.700000,2.000000,5.000000,32.592500,3.000000
50%,20.000000,6.000000,5.700000,2.530000,5.000000,1.100000,7.000000,4.000000,8.000000,66.405000,5.000000
75%,22.000000,8.025000,6.600000,3.280000,8.000000,2.100000,8.200000,5.000000,10.400000,126.242500,8.000000
max,35.000000,15.100000,9.000000,4.000000,10.000000,8.900000,11.500000,10.000000,16.700000,499.270000,20.000000

#### Variables categóricas:

Para sleep_quality, sleep_disruption_frequency, academic_work_performance y mood_swing_frequency -> codificación ordinal

withdrawal_symptoms, loss_of_other_interests, continued_despite_problems, eye_strain y back_neck_pain son binarias 

que mierda hacemos con mood_state???

In [33]:
X.describe(include='object')

,gender,game_genre,sleep_quality,sleep_disruption_frequency,academic_work_performance,mood_state,mood_swing_frequency
count,1000,1000,1000,1000,1000,1000,1000
unique,3,7,5,5,6,9,5
top,Male,MOBA,Fair,Often,Average,Normal,Sometimes
freq,647,156,293,221,246,172,214

#### Variables con valores perdidos:

como imputamos estos valores ¿?¿?

In [34]:
X.isnull().sum()

age                                   0
gender                                0
daily_gaming_hours                    0
game_genre                            0
sleep_hours                           0
sleep_quality                         0
sleep_disruption_frequency            0
academic_work_performance             0
grades_gpa                          246
work_productivity_score             326
mood_state                            0
mood_swing_frequency                  0
withdrawal_symptoms                   0
loss_of_other_interests               0
continued_despite_problems            0
eye_strain                            0
back_neck_pain                        0
weight_change_kg                      0
exercise_hours_weekly                 0
social_isolation_score                0
face_to_face_social_hours_weekly      0
monthly_game_spending_usd             0
years_gaming                          0
dtype: int64

#### Agrupar las clases a predecir para convertir el problema en un problema de clasificación binario:

La variable de salida tiene 4 categorías diferentes: Low, Moderate, High y Severe. Se juntarán Low con Moderate (formando Low Risk) y High con Severe (formando High Risk).

In [26]:
y = y.replace({
    'Low': 'Low Risk',
    'Moderate': 'Low Risk',
    'High': 'High Risk',
    'Severe': 'High Risk'
})

In [29]:
y.describe()

count         1000
unique           2
top       Low Risk
freq           704
Name: gaming_addiction_risk_level, dtype: object

#### Métrica de rendimiento:

chat si queremos ver el riesgo de volverse adicto utilizar recall por ejemplo ¿?¿?¿?